server {
    listen 8088;
    listen [::]:8088;

    server_name 136.86.164.31;

    root /var/www/devops-hackathon-de001-dinhthanh/src;
    index index.html;

    access_log /var/log/nginx/dinhdinhthanh-k24cntt1.access.log;
    error_log /var/log/nginx/dinhdinhthanh-k24cntt1.error.log;

    location / {
        allow all;
        try_files $uri $uri/ =404;
    }
}
